#!/bin/sh

echo "running precommit hook"
export LC_ALL=C

# Select files to format
GITFILES=$(git diff --name-only --cached --diff-filter=ACM "*.cs" | sed 's| |\\ |g')

[ -z "$GITFILES" ] && exit 0

echo "Files to format:"
echo "$GITFILES"

# Format only the changed files
echo "$GITFILES" | xargs dotnet-format -v diag -f

# Add back the modified files to staging
echo "$GITFILES" | xargs git add
exit 0
